---
- name: Provision an EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  # Task that will be used to Launch/Create an EC2 Instance
  tasks:
      - name: Terminate instances that were previously launched
        ec2:
            state: 'absent'
            instance_ids: '{{ instance_ids }}'
            region: '{{region}}'

